---
title: "About"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


Rohan Alexander is an assistant professor at the University of Toronto, Canada, jointly appointed in [Information](https://ischool.utoronto.ca/profile/rohan-alexander/) and [Statistical Sciences](https://www.statistics.utoronto.ca/people/directories/all-faculty/rohan-alexander). He is also a faculty affiliate at the [Schwartz Reisman Institute for Technology and Society](https://sr-institute.utoronto.ca/). He holds a PhD in Economics from the Australian National University where he was supervised by [John Tang](https://sites.google.com/view/john-tang/home) (chair), [Martine Mariotti](https://researchers.anu.edu.au/researchers/mariotti-m), [Tim Hatton](https://researchers.anu.edu.au/researchers/hatton-tj), and [Zach Ward](https://sites.google.com/site/zachaward/).

He is interested in using statistical models to try to understand the world. And particularly how we get the data that go into those models; whose data are systematically missing; how we clean, prepare, and tidy data before they are modelled; the effects of all this on the implications of our models; and how we can reproducibly share the totality of this process. This research interest has a few different applications. One of those is natural language processing (NLP), where he is interested in understanding the effects of bringing together large, biased datasets and enormous models, and how this can be improved. Another is Multilevel Regression with Post-stratification (MRP), where he examines the effects of trying to establish a correspondence between two datasets. 

He tries to develop students in his [research group](https://rohanalexander.com/group.html) that are skilled not only in using statistical methods across various disciplines, but also appreciate their limitations, and think deeply about their broader contexts of their work.

Examples of his recent [academic work](https://rohanalexander.com/academic.html) include: ['heapsofpapers'](https://rohanalexander.github.io/heapsofpapers/), ['Detecting Hate Speech with GPT-3'](https://arxiv.org/abs/2103.12407), and ['On consistency scores in text data with an implementation in R'](https://arxiv.org/abs/2101.05225).

His teaching notes are available: [Telling Stories With Data](https://www.tellingstorieswithdata.com/). He enjoys [teaching](https://rohanalexander.com/teaching.html) and aims to help students from a wide range of backgrounds learn how to use data to tell convincing stories. In Information he has taught ['Experimental Design'](https://rohanalexander.com/inf2178.html) and lead reading courses in ['Ethics and Data Science'](https://rohanalexander.com/reading_course-ethics.html), 'Information Management in Interdisciplinary Research' and 'Reproducible Data Science'. In Statistical Sciences he has taught ['Surveys, Sampling, and Observational Data'](https://rohanalexander.com/sta304.html) and lead a reading course in ['Natural Language Processing'](https://rohanalexander.com/reading_course-nlp.html). He is a [RStudio Certified Tidyverse Trainer](https://education.rstudio.com/trainers).

He co-organizes the weekly [Toronto Data Workshop](https://rohanalexander.com/toronto_data_workshop.html), which is more fun than it sounds. All welcome! Sign up [here](https://forms.gle/sXbEixoa1iJR4Q7A8).

<!-- I am organizing a conference on reproducibility in applied statistics that will be held via Zoom on Thursday and Friday 25-26 February 2021. You can learn more [here](https://rohanalexander.com/reproducibility.html).  -->

<!-- With [Lauren Kennedy](https://jazzystats.com/) at Monash University, I co-organize a weekly MRP Reading Group. Please [get in touch](mailto:rohan.alexander@utoronto.ca) if you'd like to attend. -->

<!-- Based on my academic research I run a political poll in Australia: [Petit Poll](https://petitpoll.com). This combines non-representative polling data that we gather ourselves with a hierarchical Bayesian model to cheaply deliver meaningful Australian political polling. -->

He is married to [Monica Alexander](https://www.monicaalexander.com) and they have a 2-year-old. He probably spends too much money on books, and certainly too much time at libraries (in a pre-COVID world). You can see some of the books that he recommends [here](https://rohanalexander.com/bookshelf.html). If you have any book recommendations of your own, then he'd love to hear them.

