---
title: "Forecasting the 2021 Canadian Election"
description: |
  Supported by the Canadian Election Study, CANSSI Ontario, Faculty of Information, and Department of Statistical Sciences.
bibliography: references.bib
output:
  distill::distill_article:
    toc: true
    toc_depth: 3  
---

## Overview

The 2021 Canadian Election will be held on 20 September. The [Canadian Election Study](http://www.ces-eec.ca), [CANSSI Ontario](https://canssiontario.utoronto.ca/), Faculty of Information, and Department of Statistical Sciences are calling for your best forecast for the winner of each of the 338 ridings. The three submissions will be invited to present their work at a special meeting of the Toronto Data Workshop to be held in on 1 October.

We are interested in exciting approaches that blend Canadian political understanding, statistical modelling, and data in innovative ways. We have provided some examples below, but ultimately, the approach is up to you. We are interested in who you think will win each riding, and the reasoning that underpins your approach. The full methodology must be public and reproducible to be considered.

Before the first poll closes in the eastern states, please submit a link to a GitHub repository, or Dropbox folder, that contains your data, model, and a brief write up of your approach. For ease of comparison, please also include the following [CSV](https://rohanalexander.com/images/forecast_summary.csv) with your riding-specific forecasts.

To submit your forecast, please fill out [this](https://forms.gle/Kz22435v2Z9hVJJW7) form.

The three invited groups will be:

1. The student team with the greatest number of seats correctly forecast.
2. The undergraduate team with the greatest number of seats correctly forecast (or the second closest team if the undergraduate team wins).
3. The team with the most innovative and exciting approach.

Each team may only submit one forecast. A forecast looks like (options are: LPC, CPC, BQ, NDP, GPC, Other):

riding_code  | forecast_winner
------------- | -------------
10001  | LPC
10002  | CPC
10003  | BQ
10004  | NDP
10005  | GPC
10006  | Other
...  | ...

We recommend working as part of a team, but you are welcome to work individually as well.


## Approaches


### Poll of polls

538-style poll-of-polls are popular and a useful background is provided by @jackman2005pooling. One Canadian implementation is Éric Grenier's Poll Tracker: https://newsinteractives.cbc.ca/elections/poll-tracker/canada/. 

Poll of polls models are typically national or provincial due to data availability. But in the methodology section of his website (scroll to the bottom of the page), Grenier discusses how riding-specific estimates can be created:

> The seat projection model uses a proportional swing method based on the difference between the results of the last election and current polls. For example, if a party managed 20 per cent in Quebec in the 2019 federal election and is now polling at 40 per cent in Quebec, the party's 2019 election results in each riding in Quebec are doubled. This swing is applied to every party in each riding.

One way to implement this would be to get a [list](https://en.wikipedia.org/wiki/Results_of_the_2019_Canadian_federal_election_by_riding) of the ridings and the vote share in 2019, and to then apply Grenier's provincial-specific swings to that. Some riding-specific polling is also [available](https://en.wikipedia.org/wiki/Opinion_polling_for_the_2021_Canadian_federal_election_by_constituency) and this could be used to augment such a model. Additional complications could include incumbency status and features of the local candidate, which @stevens2019local finds could be important in something like 10 per cent of contests.

Alternatively, you could construct your own poll-of-polls model. Polling data is [available](https://en.wikipedia.org/wiki/Opinion_polling_for_the_2021_Canadian_federal_election).



### Prediction markets

@omgwolfers provide an overview of the role of prediction markets and argue they 'are typically fairly accurate, and that they outperform most moderately sophisticated benchmarks'. The UBC Sauder School of Business has implemented a prediction market for the 2021 election: https://predictionmarkets.ca. This provides the essential basis of a model. 

One way to implement a riding-specific approach would be to look at the relationship between the 2019 prediction market - https://predictionmarkets.ca/CA19.php - and the actual election results.




### Economic fundamentals

@belanger_godbout_2010 implement 'a classic politico-economic model'. Their baseline model considers vote share as a function of unemployment, popularity of the governing party, and the tenure of that governing party. To implement that on a riding-specific basis: 

- Various employment-related measures are available on a riding basis from the [Canada Revenue Agency](https://www.canada.ca/en/revenue-agency/programs/about-canada-revenue-agency-cra/income-statistics-gst-hst-statistics/federal-electoral-district-statistics-feds/feds-2018.html). 
- The overall popularity of the governing party could be based on any high-quality recent poll.
- The tenure of the Liberal is known.

As our focus is riding-specific, this model could also be augmented to include the party of the incumbent in the riding.

@mongrain implements a similar model for the 2019 Canadian election and considers additional variables. 


### Kitchen sink

[338Canada](https://338canada.com/#seats) combines all of the above along with demographics to produce estimates on a riding-specific basis. Some information about methodology is available: https://338canada.blogspot.com/2018/11/welcome-to-338canada.html#metho. The essentials are similar to the Grenier uniform swing approach, with some differences due to demographics and star candidates.




### Multilevel regression with post-stratification

Multilevel regression with post-stratification (MRP) is one way to forecast an election. It trains a model on a survey, and then applies that trained model to another dataset. It can be used to generate estimates for all 338 ridings, however the trade-off is increased uncertainty. Some notes about MRP with worked examples and supporting literature are available here: https://www.tellingstorieswithdata.com/mrp.html.

If you are interested in implementing a MRP model, then please use the 2019 CES data for the 'survey'. @stephenson2021measuring provides important background. We will provide access to the following 2021 CES data - age-group, gender, highest education - after the election is finished that you can use to re-run your model and see what your model would have forecast. We are not releasing the real 2021 CES data before the election because we do not want there to be any potential concern that the CES is affecting the election in any way. 

Some post-stratification data is available [here](https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/dt-td/Rp-eng.cfm?TABID=4&LANG=E&A=R&APATH=3&DETAIL=0&DIM=0&FL=A&FREE=0&GC=01&GL=-1&GID=1324838&GK=1&GRP=1&O=D&PID=110453&PRID=10&PTYPE=109445&S=0&SHOWALL=0&SUB=0&Temporal=2017&THEME=123&VID=0&VNAMEE=&VNAMEF=&D1=0&D2=0&D3=0&D4=0&D5=0&D6=0). 



## FAQ

- How can I complicate the model? One way is to consider different functional specifications. Another way is to add additional layers to the model, for instance finding extra information about each riding (hint: maybe past vote and incumbency!) and adding that to your model. Often the best forecasts are made by teams that combine an understanding of politics with statistics. 
- Can I work as part of a team? Yes, that is recommended.

## Contact

For any questions or comments, please contact Rohan Alexander: rohan.alexander@utoronto.ca.

