---
title: "DoSS Toolkit - Call for applications"
description: |
---

**U of T students - please search the job id - 171201 Research Assistant - under oncampus jobs and associated [job posting](pdfs/RA-DoSS-toolkit_Posting_14OCT2020.pdf). For their support of this call we thank: the PIE Fund, and especially Bethany White and Radu Craiu from the Department of Statistical Sciences (DoSS).**

# Call for applications

*10 October 2020*


Are you an undergraduate or graduate student at the Univeristy of Toronto? Would you like to work with Sam-Jo Caetano and Rohan Alexander to help put together a toolkit for applied statistics? It’s focused on R essentials such as ggplot, tidyverse, GitHub, and all their friends. 

If so, please send an email to rohan.alexander@utoronto.ca with the subject line ‘DoSS toolkit application’. Please attach one PDF that contains both a cover letter and a CV. As part of your cover letter, please include a link to a GitHub repo showing off some code that you’ve written, or if you don’t have that, a blogpost you’ve written that is of a statistical/quantitative/technical nature.

Applications will be reviewed on a rolling basis, but the final deadline to apply is the end of Wednesday, 21 October 2020. 

The normal RA hourly rate and conditions will apply.

Applications from people that have been under-represented in statistical sciences are particularly encouraged. 

By way of background, we are looking to employ a small team of undergraduate and graduate students to help build a set of instructional material about R that will be used across DoSS starting in Winter (and hopefully soon after that, the broader university and community). This will build on work already done by a bunch of DoSS folks including Bethany White and Nathan Taback, and of course build on and complement the first-year courses.

You will help put together written material, videos, and assessment. You will be credited as a contributor to what will be a public-facing resource. You will have a chance to develop your R, teaching, and communication skills, as well as gain experience working in a small team.

We expect you to have some familiarity with R (i.e. have used it for a course or two), but you do NOT need to be an R expert. Indeed some successful applications may be in their first term with R.

The majority of the work will occur in early/mid November, but your appointment will run from November through to January to help deal with any lingering minor issues. The total time commitment would vary from 20 to 60 hours, depending on your circumstances and availability. The work is flexible and can be done at a time that suits you. Given we are in a pandemic, the work will be conducted remotely. Most day-to-day management will occur through Slack and GitHub.

We hope you apply!

Rohan and Sam
